version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: task_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  localstack:
    image: localstack/localstack
    container_name: task_localstack
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - ./localstack:/var/lib/localstack

volumes:
  pgdata:
